# Generated by Django 3.0.4 on 2020-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerID', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('SeniorCitizen', models.IntegerField(blank=True, max_length=255, null=True)),
                ('Partner', models.CharField(blank=True, max_length=255, null=True)),
                ('Dependents', models.CharField(blank=True, max_length=255, null=True)),
                ('tenure', models.IntegerField(blank=True, max_length=255, null=True)),
                ('PhoneService', models.CharField(blank=True, max_length=255, null=True)),
                ('MultipleLines', models.CharField(blank=True, max_length=255, null=True)),
                ('InternetService', models.CharField(blank=True, max_length=255, null=True)),
                ('OnlineSecurity', models.CharField(blank=True, max_length=255, null=True)),
                ('OnlineBackup', models.CharField(blank=True, max_length=255, null=True)),
                ('DeviceProtection', models.CharField(blank=True, max_length=255, null=True)),
                ('TechSupport', models.CharField(blank=True, max_length=255, null=True)),
                ('StreamingTV', models.CharField(blank=True, max_length=255, null=True)),
                ('StreamingMovies', models.CharField(blank=True, max_length=255, null=True)),
                ('Contract', models.CharField(blank=True, max_length=255, null=True)),
                ('PaperlessBilling', models.CharField(blank=True, max_length=255, null=True)),
                ('PaymentMethod', models.CharField(blank=True, max_length=255, null=True)),
                ('MonthlyCharges', models.IntegerField(blank=True, max_length=255, null=True)),
                ('TotalCharges', models.IntegerField(blank=True, max_length=255, null=True)),
                ('Churn', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
